apiVersion: 1

policies:
  - orgId: 1
    receiver: "telegram-alerts"
    group_by:
      - "alertname"
      - "severity"
    group_wait: "10s"
    group_interval: "5m"
    repeat_interval: "1h"
    routes:
      - receiver: "telegram-critical"
        object_matchers:
          - ["severity", "=", "critical"]
        group_wait: "5s"
        group_interval: "2m"
        repeat_interval: "10m"
      - receiver: "telegram-warnings"
        object_matchers:
          - ["severity", "=", "warning"]
        group_wait: "10s"
        group_interval: "5m"
        repeat_interval: "30m"

templates:
  - name: "telegram-template"
    template: |
      {{ define "telegram.title" }}
      🚨 {{ .GroupLabels.alertname }}
      {{ end }}
      
      {{ define "telegram.message" }}
      **Alert:** {{ .GroupLabels.alertname }}
      **Severity:** {{ .GroupLabels.severity }}
      **Service:** {{ .GroupLabels.service }}
      **Component:** {{ .GroupLabels.component }}
      
      {{ range .Alerts }}
      **Summary:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ if .EndsAt }}**Resolved:** {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
      {{ end }}
      
      🔗 [View Dashboard](http://localhost:3000)
      📊 [View Metrics](http://localhost:9090)
      {{ end }}

contactPoints:
  - orgId: 1
    name: "telegram-alerts"
    receivers:
      - uid: "telegram_general"
        type: "telegram"
        settings:
          botToken: "8477234765:AAGSEYtyTJBVihV0whck8ZyUTYeZ8l9IoV0"
          chatId: "845749173"
          parseMode: "Markdown"
          message: '{{ template "telegram.message" . }}'
          title: '{{ template "telegram.title" . }}'
  
  - orgId: 1
    name: "telegram-critical"
    receivers:
      - uid: "telegram_critical"
        type: "telegram"
        settings:
          botToken: "YOUR_TELEGRAM_BOT_TOKEN"
          chatId: "YOUR_CHAT_ID"
          parseMode: "Markdown"
          message: |
            🔥 **CRITICAL ALERT**
            
            **Alert:** {{ .GroupLabels.alertname }}
            **Service:** {{ .GroupLabels.service }}
            **Severity:** {{ .GroupLabels.severity }}
            
            {{ range .Alerts }}
            **Summary:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
            
            🔗 [View Dashboard](http://localhost:3000)
  
  - orgId: 1
    name: "telegram-warnings"
    receivers:
      - uid: "telegram_warnings"
        type: "telegram"
        settings:
          botToken: "8477234765:AAGSEYtyTJBVihV0whck8ZyUTYeZ8l9IoV0"
          chatId: "845749173"
          parseMode: "Markdown"
          message: |
            ⚠️ **WARNING ALERT**
            
            **Alert:** {{ .GroupLabels.alertname }}
            **Service:** {{ .GroupLabels.service }}
            **Severity:** {{ .GroupLabels.severity }}
            
            {{ range .Alerts }}
            **Summary:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
            
            🔗 [View Dashboard](http://localhost:3000)
